export const RESTAURANTS = [
  {
    id: 0,
    name: "Kopi Susu Tetangga",
    store: "Tuku",
    location: "GBI Arena, Central Jakarta",
    price: "IDR 20.000",
    description:
      "If anyone ask what's my goto coffee shop, this is it. It's sweet aren makes the coffee creamy and aromatic. They've got plenty of branches across Jakarta. I highly recommend it.",
    gMaps: "https://maps.app.goo.gl/5YX6GV7jnUv5YupM9",
    image: "",
    taste: 5,
    ambience: 5,
    worth: 5,
  },
  {
    id: 1,
    name: "Koko Curry Mee",
    store: "Naked Papa",
    location: "Kembangan, West Jakarta",
    price: "IDR 45.000",
    description:
      "Great curry noodles with pork, doesn't make you feel heavy when finishing this. They got a good selection of coffee and basque cheesecake too.",
    gMaps: "https://maps.app.goo.gl/eaYFbZx3jrMmMYQq6",
    image:
      "https://assets-pergikuliner.com/Kl6P3ymV1-XhSxrh2jSrMjTx97I=/312x0/smart/https://assets-pergikuliner.com/uploads/image/picture/3249911/picture-1714534083.jpg",
    taste: 5,
    ambience: 5,
    worth: 3.5,
  },
  {
    id: 2,
    name: "Bakmie Rica-Rica",
    store: "Bakmie Nirwana",
    location: "Kembangan, West Jakarta",
    price: "IDR 45.000",
    description:
      "The OG whole-some & feel at home bakmie stall, price might be above average, but the bakmie rica is different from any other bakmie out there. Service isn't the best but its quick and delicious. The stall started from selling bakmie in front of the akong's house to now opening its own stall in a wider area.",
    gMaps: "https://g.co/kgs/Z2MV3TH",
    image: "",
    taste: 5,
    ambience: 3,
    worth: 4,
  },
  {
    id: 3,
    name: "Pigcasso Rice Bowl",
    store: "Pigcasso",
    location: "Puri Indah Mall, West Jakarta",
    price: "IDR 60.000",
    description:
      "If you're looking for a fancy and comfortable place to eat crispy pork, this place is it. You can have your pork the traditional way with rice, or the modern way with pasta.",
    gMaps: "https://maps.app.goo.gl/NtqBuxVsR895TLyFA",
    image: "",
    taste: 5,
    ambience: 4.5,
    worth: 4,
  },
  {
    id: 4,
    name: "Gen-Matcha",
    store: "Kancha Tea Hub",
    location: "Puri Indah Mall, West Jakarta",
    price: "IDR 30.000 (L)",
    description:
      "For the tea enthusiast and workaholic who'd like to work in a peaceful cafe this is the place to stop by. Great selection of fresh artisan teas. Their matcha however is one to highlight, with its nutty and unique taste.",
    gMaps: "https://maps.app.goo.gl/c7V6RjyNtAjQgKu67",
    image: "",
    taste: 4,
    ambience: 5,
    worth: 4.5,
  },
];
