export const RESTAURANTS = [
  {
    id: 1,
    name: "Kopi Susu Tetangga",
    store: "Tuku",
    location: "GBK Arena, Central Jakarta",
    price: "IDR 20,000",
    description:
      "If you're wondering about my go-to coffee spot, it's right here. The sweet aren sugar makes the coffee extra creamy and aromatic, creating a flavor profile that's hard to forget. With plenty of branches across Jakarta, it's a must-try for coffee lovers everywhere. Highly recommended!",
    gMaps: "https://maps.app.goo.gl/5YX6GV7jnUv5YupM9",
    image: "https://cdn-khub.istyle.id/650/uploads/images/2017/08/5-3.jpg",
    taste: 5,
    ambience: 5,
    worth: 5,
    className: "tuku",
  },
  {
    id: 2,
    name: "Koko Curry Mee",
    store: "Naked Papa",
    location: "Kembangan, West Jakarta",
    price: "IDR 45,000",
    description:
      "Delicious curry noodles crafted by MasterChef @Willgoz! The flavors are rich but light enough to keep you craving more with every bite. Besides the curry mee, they offer a great coffee selection and a must-try Basque cheesecake. Traditional Bakmie and pork rice dishes are also on the menu – comfort food perfected.",
    gMaps: "https://maps.app.goo.gl/eaYFbZx3jrMmMYQq6",
    image:
      "https://cdn.idntimes.com/content-images/post/20240304/whatsapp-image-2024-03-04-at-082617-b94395cf8741de14fd0f4eef92c5d3c5.jpeg",
    taste: 5,
    ambience: 5,
    worth: 3.5,
    className: "naked-papa",
  },
  {
    id: 3,
    name: "Bakmie Rica-Rica",
    store: "Bakmie Nirwana",
    location: "Kembangan, West Jakarta",
    price: "IDR 45,000",
    description:
      "A true gem! This OG bakmie stall serves up a hearty, home-style feel with its unique rica flavor. The price may be above average, but the taste and portion make it worthwhile. Though service is straightforward, it's quick, and the bakmie is truly delicious. Started as a small stall in front of the owner's house, they've now expanded into a full eatery.",
    gMaps: "https://g.co/kgs/Z2MV3TH",
    image: "/images/foods/bakmie_nirwana.jpeg",
    taste: 5,
    ambience: 3,
    worth: 4,
    className: "nirwana",
  },
  {
    id: 4,
    name: "Gen-Matcha",
    store: "Kancha Tea Hub",
    location: "Puri Indah Mall, West Jakarta",
    price: "IDR 30,000 (L)",
    description:
      "Perfect for tea enthusiasts and remote workers alike, this cafe offers a peaceful escape with an amazing selection of artisan teas. The star of the show is their matcha, which boasts a nutty, unique taste that’s sure to leave an impression. If you appreciate a refined tea experience, Kancha Tea Hub won’t disappoint.",
    gMaps: "https://maps.app.goo.gl/c7V6RjyNtAjQgKu67",
    image:
      "https://dzglkev4c34xb.cloudfront.net/horego.com/sawah-besar/restaurant/kancha-pos-bloc/food/af1qipobuqitk8lk5yf8efcd-vjmopw9m4vgt4b-uew3.jpg",
    taste: 4,
    ambience: 5,
    worth: 4.5,
    className: "kancha",
  },
  {
    id: 5,
    name: "Aroma Dia (Creamy)",
    store: "Suasanakopi",
    location: "Blok M, South Jakarta",
    price: "IDR 35,000",
    description:
      "Get your caffeine fix at this industrial-chic cafe, where the aroma of freshly brewed coffee fills the air. Plus, indulge in their delicious pastries to pair with your coffee! It's a great spot for remote workers, with a compact but cozy space that's perfect for getting things done. Just be prepared to fight for a seat!",
    gMaps: "https://maps.app.goo.gl/YbhYgVCqE1JNyvQGA",
    image: "https://pbs.twimg.com/media/FiqGLKkacAcjn2C?format=jpg&name=large",
    taste: 4.5,
    ambience: 4.5,
    worth: 4,
    className: "suasanakopi",
  },
  {
    id: 6,
    name: "Es Kopi Susu Sinilagi",
    store: "SiniLagi",
    location: "Puri, West Jakarta",
    price: "IDR 35,000",
    description:
      "Coffee with gula aren - it's perfectly sweet. Similar to Naked Papa, they serve bakmie noodles here too. The place is best known for their polo buns, but as a non-bread person, I haven't tried them. However, people always buy them, so they should be good. It can get pretty crowded on weekends though.",
    gMaps: "https://maps.app.goo.gl/vAJMdZuu4fFyZEEa9",
    image: "/images/foods/sinilagi.jpeg",
    taste: 4,
    ambience: 5,
    worth: 4,
    className: "sinilagi",
  },
];
